spring.application.name=projet-enchere

#Connexion à la base de données
spring.datasource.url=jdbc:sqlserver://localhost:1433;databasename=projet-enchere;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=SA
spring.datasource.password=Pa$$w0rd
#Détail des requêtes pour le développement
logging.level.org.springframework.jdbc.core=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
#Deconnection après inactivite (5 minutes)
server.servlet.session.timeout=5m
