spring.application.name=projet-enchere

#Connexion à la base de données
spring.datasource.url=jdbc:sqlserver://localhost:1433;databasename=projet-enchere;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd
#Détail des requêtes pour le développement
logging.level.org.springframework.jdbc.core=TRACE